apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: weedweek
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:5.9.1-php8.0-apache
          resources:
            limits:
              cpu: "1200m"
              memory: "1000M"
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb.database
            - name: WORDPRESS_DB_USER
              value: weedweek
            - name: WORDPRESS_DB_PASSWORD
              value: M2FkZWFhNDNkMWFlZTE2NDNhMGFkZjRj
            - name: WORDPRESS_DB_NAME
              value: weedweek
            - name: WORDPRESS_TABLE_PREFIX
              value: '420_'
          volumeMounts:
            - name: storage
              mountPath: /var/www/html
          ports:
            - containerPort: 80
      volumes:
        - name: storage
          awsElasticBlockStore:
            volumeID: 'vol-0f5d991e653a8bd00'
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: weedweek
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: weedweek
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
spec:
  tls:
    - hosts:
        - admin.weedweek.pl
      secretName: weedweek-wordpress-ingress-tls
  rules:
    - host: admin.weedweek.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-redirect
  namespace: weedweek
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-http-to-https@kubernetescrd
spec:
  rules:
    - host: admin.weedweek.pl
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: wordpress
                port:
                  number: 80
